#!/bin/bash
#FONCTIONNALITES ENVOI CLES
function envoi-cle()
{
	echo -e "\n\t---> VEUILLEZ    ENTREZ    L'   ADRESSE    IP    DU     SERVEUR   :  "
	read ipserverenvoi
	echo -e "\n\t---> ENTREZ  LE  PORT   DU   SERVEUR   :   ( PORT  22  PAR  DEFAUT )   "
	read portserverenvoi
	echo -e "\n\t---> ENTREZ LE NOM DU COMPTE SERVEUR OU VOUS VOULEZ FAIRE L' ENVOI  :   "
	read nomserverenvoi
	if test -d ~/Bureau/Paire-Cles
	then 
		case $ipserverenvoi in
			#(([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$))
			[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*)
				case $portserverenvoi in
					0*)
						if [ -e ~/Bureau/Paire-Cles/id_rsa ] 
						then
							mv ~/Bureau/Paire-Cles/id_rsa ~/.ssh >> log.txt 2>&1
							mv ~/Bureau/Paire-Cles/id_rsa.pub ~/.ssh >> log.txt 2>&1
							rm -r ~/Bureau/Paire-Cles >> log.txt 2>&1
							ssh-copy-id -i ~/.ssh/id_rsa.pub $nomserverenvoi@$ipserverenvoi >> log.txt 2>&1
							if [ $? -ne 0 ] 
							then
								echo -e "\n\t UN  PROBLEME  EST  SURVENU  LORS DE  L' ENVOI. VEUILLEZ REESAYER "
								echo -e "\t     ULTERIEUREMENT. APPUYEZ SUR UNE TOUCHE POUR REVENIR AU     "
								echo -e "\t                          MENU PRINCIPAL !                        "
								appui
								menu-mode-client
							fi
						else 
							echo -e "\n\t  LA  CLE  EST  INTROUVABLE. APPUYER  SUR  UNE TOUCHE POUR REVENIR AU "
							echo -e "\t                           MENU    PRINCIPAL.                           "
							appui
							menu-mode-client
						fi
					;;	                         
					[1-9]*)				
						if [ -e ~/Bureau/Paire-Cles/id_rsa ] 
						then
							cp ~/Bureau/Paire-Cles/id_rsa ~/.ssh >> log.txt 2>&1
							cp ~/Bureau/Paire-Cles/id_rsa.pub ~/.ssh >> log.txt 2>&1
							timeout 10s ssh-copy-id -i ~/.ssh/id_rsa.pub -p $portserverenvoi $nomserverenvoi@$ipserverenvoi >> log.txt 2>&1
                            if [ $? -ne 0 ] 
							then
								echo -e "\n\t UN  PROBLEME  EST  SURVENU  LORS DE  L' ENVOI. VEUILLEZ REESAYER "
								echo -e "\t     ULTERIEUREMENT. APPUYEZ SUR UNE TOUCHE POUR REVENIR AU     "
								echo -e "\t                          MENU PRINCIPAL !                        "
								appui
								menu-mode-client
							fi
						else 
							echo -e "\n\t  LA  CLE  EST  INTROUVABLE. APPUYER  SUR  UNE TOUCHE POUR REVENIR AU "
							echo -e "\t                           MENU    PRINCIPAL.                           "
							appui
							menu-mode-client
						fi
					;;
					*)
						echo -e "\n\t  LE  PORT  EST  INCORRECT. APPUYEZ  SUR  UNE  TOUCHE POUR REVENIR AU "
						echo -e "\t                          MENU    PRINCIPAL.                            "
						appui
						menu-mode-client
					;;
				esac
			;;
			*)
				echo -e "\n\t  L' ADRESSE IP EST INCORRECT. APPUYEZ SUR  UNE TOUCHE POUR REVENIR AU "
				echo -e "\t                           MENU    PRINCIPAL.                            "
				appui
				menu-mode-client
			;;
		esac
	else 
		echo -e "\n\t  LA  CLE  EST  INTROUVABLE. APPUYER  SUR  UNE TOUCHE POUR REVENIR AU "
		echo -e "\t                          MENU    PRINCIPAL.                            "
		appui
		menu-mode-client
	fi  
	echo -e "\n\tL' ENVOI DES CLES S' EST EFFECTUE SANS PROBLEME. VOUS POUVEZ DES " 
	echo -e   "\t  A PRESENT  VOUS CONNECTEZ  A L' AIDE DE VOTRE PASSPHRASE !!!   "
    rm -r ~/Bureau/Paire-Cles >> log.txt 2>&1 
}

#FONCTIONNALITES CONNEXION
function connexion()
{
	echo -e "\n\t---> VEUILLEZ    ENTREZ    L'   ADRESSE    IP    DU     SERVEUR   :  \n"
	read ipserver
	echo -e "\n\t---> ENTREZ  LE  PORT   DU   SERVEUR   :   ( PORT  22  PAR  DEFAUT )   \n"
	read portserver
	echo -e "\n\t---> ENTREZ LE NOM DU COMPTE SERVEUR OU VOUS VOULEZ FAIRE L' ENVOI  :   \n"
	read nomserver
	case $ipserver in
		#(([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$))
		[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*)
			case $portserver in
				0*)
					portserver=22
					gnome-terminal -e 'bash -c "sleep 3;ssh $nomserver@$ipserver"' >> log.txt 2>&1
					if [ $? -ne 0 ] 
						then
							echo -e "\n\tUN PROBLEME  EST SURVENU LORS DE  LA CONNEXION. VEUILLEZ REESAYER "
							echo -e "\t     ULTERIEUREMENT. APPUYEZ SUR UNE TOUCHE POUR REVENIR AU     "
							echo -e "\t                          MENU PRINCIPAL !                        "
							appui
							menu-mode-client
					fi
				;;	                         
				[1-9]*)				
					gnome-terminal -e 'bash -c "sleep 3;ssh -p $portserver $nomserver@$ipserver"' >> log.txt 2>&1
					if [ $? -ne 0 ] 
						then
							echo -e "\n\tUN PROBLEME  EST SURVENU LORS DE  LA CONNEXION. VEUILLEZ REESAYER "
							echo -e "\t     ULTERIEUREMENT. APPUYEZ SUR UNE TOUCHE POUR REVENIR AU     "
							echo -e "\t                          MENU PRINCIPAL !                        "
							appui
							menu-mode-client
					fi
				;;
				*)
					echo -e "\n\t LE  PORT  EST  INCORRECT. APPUYEZ  SUR  UNE  TOUCHE POUR REVENIR AU "
					echo -e "\t                        MENU    PRINCIPAL.                             "
					appui
					menu-mode-client
				;;
			esac
		;;	
		*)
			echo -e "\n\tL' ADRESSE IP EST INCORRECT. APPUYEZ SUR  UNE TOUCHE POUR REVENIR AU "
			echo -e "\t                         MENU    PRINCIPAL.                            "
			appui
			menu-mode-client
		;;
	esac
	echo -e "\n\t         VOUS  ETES  A  PRESENT  CONNECTE AU SERVEUR !!           "
	echo -e   "\t                  -------------------------                       "
}

# SOUS MENU ENVOI  DES  CLES
function menu-fonct-server-envoi()
{
    resize -s 26 84
    clear
    echo -e    "|**********************************************************************************|"
    echo -e    "|                                                                                  |"
    echo -e    "|\t \t \t    FONCTIONNALITES    DU     SERVEUR\t\t\t\t|"
	echo -e    "|                                                                                  |"
	echo -e    "|**********************************************************************************|"
    echo -e    "|                                                                                  |"
    echo -e    "|\t\t\t          ENVOI   DES   CLES\t \t \t\t   |"
    echo -e    "|                                                                                  |"
	echo -e    "|**********************************************************************************|"
    echo -e    "|                                                                                  |"
    echo -e    "| CETTE ETAPE A POUR BUT DE VOUS AIDER A ENVOYER VOTRE PAIRE DE CLES, QUI VOUS AI- |"
    echo -e    "|  DERA A VOUS AUTHENTIFIER AU PRES DE VOTRE SERVEUR. NOTEZ QUE POUR CETTE ETAPE,  |"
    echo -e    "|  IL EST NECESSAIRE D' AVOIR LE MOT DE PASSE DU SERVEUR EN VOTRE POSSESION, FAUTE |"
    echo -e    "|    DE QUOI ON VOUS INDIQUERA COMMENT FAIRE POUR ENVOYER VOTRE CLE PUBLIQUE AU    |"
    echo -e    "|                                 SERVEUR !!!                                      |"
    echo -e    "|                                                                                  |"
	echo -e    "|**********************************************************************************|"
    envoi-cle
    echo -e    "   APPUYEZ   SUR    UNE    TOUCHE   POUR    REVENIR   AUX    FONCTIONNALITES       "
    appui
    menu-fonct-server      
}

# SOUS MENU POUR LA CONNEXION  AU SERVEUR
function menu-fonct-server-conn()
{
    resize -s 21 83
    clear
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t    FONCTIONNALITES    DU     SERVEUR\t\t\t\t|"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t          CONNEXION  AU  SERVEUR\t\t\t\t|"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    connexion
    connexion_client=0
    echo -e    "\n   APPUYEZ   SUR    UNE    TOUCHE   POUR    REVENIR   AUX    FONCTIONNALITES       "
    appui
    menu-fonct-server
}

#SOUS  MENU  POUR  LA  DECONNECTION 
function menu-fonct-server-deconn()
{
    resize -s 17 83
    clear
    connexion_client=1
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t    FONCTIONNALITES    DU     SERVEUR\t\t\t\t|"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t        DECONNEXION  AU  SERVEUR\t\t\t\t|"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|       IL  SUFFIT  JUSTE   DE  FERMER  LE   TERMINAL  DU   SERVEUR !!!           |"
    echo -e    "|                                                                                 |"
    echo -e    "|    APPUYEZ   SUR   UNE   TOUCHE   POUR  REVENIR   AU   MENU   PRINCIPAL !       |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    appui
    menu-mode-client
}

# MENU PRINCIPAL FONCTIONNALITES  SERVEUR
function menu-fonct-server()
{
    resize -s 18 83
    clear
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t   FONCTIONNALITES   DU    SERVEUR\t\t\t\t|"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e "\n \n"
    
    #VARIABLES DU MENU

    me1="\t Envoi  de  la  cle  publique       au   serveur"
    me2="\t Connexion  \t     au    \t    serveur \n"
    me3="\t Deconnexion  \t     du    \t    serveur \n"
    me4="\t Revenir  \t     au  \t    mode    Client  \n"
    me5="\t Quitter"
 
    me1=`echo -e "$me1"`
    me2=`echo -e "$me2"`
    me3=`echo -e "$me3"`
    me4=`echo -e "$me4"`
    me5=`echo -e "$me5"`
    
    #CHOIX DU MENU

    PS3="`echo -e " \n\n Veuillez \t faire  \t  votre  \t  choix :     "`"

    select var in "$me1" "$me2" "$me3" "$me4" "$me5"
    do 
        case $REPLY in 
			1)	
                menu-fonct-server-envoi		
                break
            ;;
    		2)
                menu-fonct-server-conn		
                break
			;;
            3)
                if [ $connexion_client -eq 1 ] 
                    then
                        echo -e " \n Vous   devez   d'   abord    etre   connecte     !"
                    else
                        menu-fonct-server-deconn
                        break
                fi
			;;
            4)
                menu-mode-client	
                break
			;;
            5)	
				exit
			;;
            *)
                PS3="`echo -e " \n Veuillez       faire       un       choix       valide :     "`"
            ;;
		esac	
    done    
}