#!/bin/bash

# FONCTIONNALITES DOWNLOAD SCP
function download-scp()
{
	echo -e    "\n ---->   Indiquez  le  chemin  source  (repertoire dans le serveur)            \n"
    read sourc
    echo -e    "\n ---->   Indiquez  le  chemin   de   destination  (repertoire dans le client)  \n"
    read desti
    scp -r $nomserver@$ipserver:$sourc $desti >> log.txt 2>&1
	if [ $? -ne 0 ] 
		then
			echo -e "\n\t UN  PROBLEME  EST  SURVENU  LORS DE  LA COPIE. VEUILLEZ REESAYER "
			echo -e "\t     ULTERIEUREMENT. APPUYEZ SUR UNE TOUCHE POUR REVENIR AU     "
			echo -e "\t                          MENU PRINCIPAL !                        "
			appui
			menu-mode-client
	fi
    echo -e    "\n                  VOTRE     COPIE     A     ETE     EFFECTUEE   !!!\n" 
}

#FONCTIONNALITES DOWNLOAD SFTP
function download-sftp()
{
	echo -e    "\n ---->   Indiquez  le  chemin  source  (repertoire dans le serveur)            \n"
    read sourc
    echo -e    "\n ---->   Indiquez  le  chemin   de   destination  (repertoire dans le client)  \n"
    read desti
    echo "get -r $sourc $desti" | sftp -o Port=$portserver  $nomserver@$ipserver >> log.txt 2>&1
	if [ $? -ne 0 ] 
		then
			echo -e "\n\t UN  PROBLEME  EST  SURVENU  LORS DE  LA COPIE. VEUILLEZ REESAYER "
			echo -e "\t     ULTERIEUREMENT. APPUYEZ SUR UNE TOUCHE POUR REVENIR AU     "
			echo -e "\t                          MENU PRINCIPAL !                        "
			appui
			menu-mode-client
	fi
    echo -e    "\n                  VOTRE     COPIE     A     ETE     EFFECTUEE   !!!\n" 
}

# FONCTIONNALITES UPLOAD SCP
function upload-scp()
{
	echo -e    "\n ---->   Indiquez  le  chemin  source : (repertoire dans le client)            \n"
    read sourc
    echo -e    "\n ---->   Indiquez  le  chemin  de   destination : (repertoire dans le serveur)  \n"
    read desti
    scp -r $sourc $nomserver@$ipserver:$desti >> log.txt 2>&1
	if [ $? -ne 0 ] 
		then
			echo -e "\n\t UN  PROBLEME  EST  SURVENU  LORS DE  LA COPIE. VEUILLEZ REESAYER "
			echo -e "\t     ULTERIEUREMENT. APPUYEZ SUR UNE TOUCHE POUR REVENIR AU     "
			echo -e "\t                          MENU PRINCIPAL !                        "
			appui
			menu-mode-client
	fi
    echo -e    "\n                  VOTRE     COPIE     A     ETE     EFFECTUEE   !!!\n" 
}

#FONCTIONNALITES UPLOAD SFTP
function upload-sftp()
{
	echo -e    "\n ---->   Indiquez  le  chemin  source : (repertoire dans le client)            \n"
    read sourc
    echo -e    "\n ---->   Indiquez  le  chemin  de   destination : (repertoire dans le serveur)  \n"
    read desti
    echo "put -r $sourc $desti" | sftp -o Port=$portserver  $nomserver@$ipserver >> log.txt 2>&1
	if [ $? -ne 0 ] 
		then
			echo -e "\n\t UN  PROBLEME  EST  SURVENU  LORS DE  LA COPIE. VEUILLEZ REESAYER "
			echo -e "\t     ULTERIEUREMENT. APPUYEZ SUR UNE TOUCHE POUR REVENIR AU     "
			echo -e "\t                          MENU PRINCIPAL !                        "
			appui
			menu-mode-client
	fi
    echo -e    "\n                  VOTRE     COPIE     A     ETE     EFFECTUEE   !!!\n" 
}

#FONCTIONNALITES MONTAGE REPERTOIRE
function montage()
{
    echo -e "\n--> Indiquez  le  chemin  du  repertoire  distant  (repertoire dans le serveur)  \n"	
	read repdistant
	echo -e "\n--> Indiquez  le  chemin  du  repertoire  local ou il sera stocke (repertoire client) \n"
	read repmonte
	sshfs $nomserver@$ipserver:$repdistant $repmonte -o nonempty >> log.txt 2>&1
	if [ $? -ne 0 ] 
		then
			echo -e "\n\t UN  PROBLEME  EST  SURVENU  LORS  DU  MONTAGE. VEUILLEZ REESAYER "
			echo -e "\t     ULTERIEUREMENT. APPUYEZ SUR UNE TOUCHE POUR REVENIR AU     "
			echo -e "\t                          MENU PRINCIPAL !                        "
			appui
			menu-mode-client
	fi
	echo -e "\n             VOTRE    MONTAGE    A     ETE     EFFECTUE   !!!"
	echo -e   "                  ---------------------------------          "
}

#FONCTIONNALITES DEMONTAGE REPERTOIRE
function demontage()
{
	echo -e    "\n-->  Indiquez  le  chemin  du repertoire ou s' est effectue le montage :        \n"
	read rep
	fusermount -u $rep >> log.txt 2>&1
	if [ $? -ne 0 ] 
		then
			echo -e "\n\tUN  PROBLEME  EST  SURVENU  LORS  DU  DEMONTAGE. VEUILLEZ REESAYER "
			echo -e "\t     ULTERIEUREMENT. APPUYEZ SUR UNE TOUCHE POUR REVENIR AU     "
			echo -e "\t                          MENU PRINCIPAL !                        "
			appui
			menu-mode-client
	fi
	echo -e "\n            VOTRE    DEMONTAGE    A     ETE     EFFECTUE   !!!"
	echo -e   "                  ---------------------------------          "
}

#FONCTIONNALITES REDIRECTION LOCALE
function redirection-loc()
{
    echo -e    "\n--->  Indiquez  le  port du  serveur auquel vous souhaitez acceder :   \n"
    read dist
    echo -e    "\n--->  Indiquez  le  port local qui vous permettra d' acceder au port distant : \n"
    read loc
    export loc
    export dist
	gnome-terminal -e 'bash -c "resize -s 10 10;clear;clear;echo \"REDIRECTION EN COURS...\";ssh $nomserver@$ipserver -NL$loc:localhost:$dist"' >> log.txt 2>&1
	if [ $? -ne 0 ] 
		then
			echo -e "\n\tUN  PROBLEME  EST  SURVENU  LORS  DE  LA REDIRECTION. VEUILLEZ REESAYER "
			echo -e "\t     ULTERIEUREMENT. APPUYEZ SUR UNE TOUCHE POUR REVENIR AU     "
			echo -e "\t                          MENU PRINCIPAL !                        "
			appui
			menu-mode-client
	fi
	echo -e "\t  POUR  ACCEDER  AU  PORT  $dist DU SERVEUR IL VOUS SUFFIRA D' ENTRER    "
	echo -e "\t    localhost:$loc  DANS  VOTRE  NAVIGUATEUR. POUR ARRETER LA REDI-      "
	echo -e "\t          RECTION IL SUFFIT DE FERMER LE MINI TERMINAL.                  "  
}

#FONCTIONNALITES SECURISATION 
function securisation()
{
    echo -e    "\n ---->   Indiquez  le  port que vous souhaitez securise :                        \n"
    read loc
    echo -e    "\n ---->   Indiquez  le  port qui devra le remplacer  sur le serveur:              \n"
    read dist
	gnome-terminal -e 'bash -c "resize -s 10 10;clear;clear;echo \"REDIRECTION EN COURS...\";ssh $nomserver@$ipserver -NR$dist:localhost:$loc"' >> log.txt 2>&1
	if [ $? -ne 0 ] 
		then
			echo -e "\n\tUN  PROBLEME  EST  SURVENU  LORS  DE  LA REDIRECTION. VEUILLEZ REESAYER "
			echo -e "\t     ULTERIEUREMENT. APPUYEZ SUR UNE TOUCHE POUR REVENIR AU     "
			echo -e "\t                          MENU PRINCIPAL !                        "
			appui
			menu-mode-client
	fi
	echo -e "\t  POUR  ACCEDER  AU  PORT  $loc  DU  CIENT  IL VOUS SUFFIRA D' ENTRER    "
	echo -e "\t  localhost:$dist DANS LE NAVIGUATEUR DU SERVEUR. POUR ARRETER LA REDI-  "
	echo -e "\t          RECTION IL SUFFIT DE FERMER LE MINI TERMINAL.                  "  
}

# SOUS MENU POUR LE DOWNLOAD VIA SCP
function menu-fonct-client-down-scp()
{
    resize -s 26 83
    clear
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t   FONCTIONNALITES   DU    CLIENT \t\t\t\t|"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t      TRANSFERT   DE   FICHIERS\t \t \t\t  |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t         DOWNLOAD   VIA   SCP  \t \t \t\t  |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    download-scp
    echo -e    "   APPUYEZ   SUR    UNE    TOUCHE   POUR    REVENIR   AUX    FONCTIONNALITES       "
    appui
    menu-fonct-client
}

#SOUS MENU POUR LE DOWNLOAD VIA SFTP
function menu-fonct-client-down-sftp()
{
    resize -s 28 83
    clear
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t   FONCTIONNALITES   DU    CLIENT \t\t\t\t|"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t      TRANSFERT   DE   FICHIERS\t \t \t\t  |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t         DOWNLOAD   VIA   SFTP \t \t \t\t  |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "| VOUS  POUVEZ  MONTER VIRTUELLEMENT UN REPERTOIRE DISTANT AFIN DE FACILITER VOS  |"
    echo -e    "|   COPIES  EN ENTRANT sftp://monlogin@monserveur DANS LA BARRE D' ADRESSE DE     |"
    echo -e    "|                      VOTRE GESTIONNAIRE  DE  FICHIERS.                          |"
    echo -e    "|*********************************************************************************|"
    download-sftp
    echo -e    "   APPUYEZ   SUR    UNE    TOUCHE   POUR    REVENIR   AUX    FONCTIONNALITES       "
    appui
    menu-fonct-client
}

# SOUS MENU POUR L UPLOAD VIA SCP
function menu-fonct-client-up-scp()
{
    resize -s 26 83
    clear
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t   FONCTIONNALITES   DU    CLIENT \t\t\t\t|"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t      TRANSFERT   DE   FICHIERS\t \t \t\t  |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t          UPLOAD    VIA   SCP  \t \t \t\t  |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    upload-scp
    echo -e    "   APPUYEZ   SUR    UNE    TOUCHE   POUR    REVENIR   AUX    FONCTIONNALITES       "
    appui
    menu-fonct-client
}

#SOUS MENU POUR LE UPLOAD VIA SFTP
function menu-fonct-client-up-sftp()
{
    resize -s 28 83
    clear
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t   FONCTIONNALITES   DU    CLIENT \t\t\t\t|"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t      TRANSFERT   DE   FICHIERS\t \t \t\t  |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t          UPLOAD    VIA   SFTP \t \t \t\t  |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "| VOUS  POUVEZ  MONTER VIRTUELLEMENT UN REPERTOIRE DISTANT AFIN DE FACILITER VOS  |"
    echo -e    "|   COPIES  EN ENTRANT sftp://monlogin@monserveur DANS LA BARRE D' ADRESSE DE     |"
    echo -e    "|                      VOTRE GESTIONNAIRE  DE  FICHIERS.                          |"
    echo -e    "|*********************************************************************************|"
    upload-sftp
    echo -e    "   APPUYEZ   SUR    UNE    TOUCHE   POUR    REVENIR   AUX    FONCTIONNALITES       "
    appui
    menu-fonct-client
}

# SOUS MENU POUR LE TRANSFERT DE FICHIERS
function menu-fonct-client-transf()
{
    resize -s 25 83
    clear
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t   FONCTIONNALITES   DU    CLIENT \t\t\t\t|"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t      TRANSFERT   DE   FICHIERS\t \t \t\t  |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|  NOTEZ QUE SFTP VOUS OFFRE LA POSSIBILITE D' UTILISER VOTRE GESTIONNAIRE DE FI- |"
    echo -e    "|            CHIERS POUR EFFECTUER DES COPIES CONTRAIREMENT A SCP.                |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
     echo -e "\n"
    
    #VARIABLES DU MENU

    me1="\t Download   \t  via  \t  SCP \n\n"
    me2="\t Download   \t  via  \t  SFTP \n"
    me3="\t Upload     \t  via  \t  SCP \n\n"
    me4="\t Upload     \t  via  \t  SFTP \n"
    me5="\t Retourner  \t  aux  \t  fonctionnalites "

    me1=`echo -e "$me1"`
    me2=`echo -e "$me2"`
    me3=`echo -e "$me3"`
    me4=`echo -e "$me4"`
    me5=`echo -e "$me5"`
    
    #CHOIX DU MENU

    PS3="`echo -e " \n\n\n Veuillez \t faire  \t  votre  \t  choix :     "`"

    select var in "$me1" "$me2" "$me3" "$me4" "$me5"
    do 
        case $REPLY in 
			1)	
                menu-fonct-client-down-scp		
                break
            ;;
    		2)
                menu-fonct-client-down-sftp		
                break
			;;
            3)	
                menu-fonct-client-up-scp		
                break
            ;;
    		4)
                menu-fonct-client-up-sftp		
                break
			;;
        	5)	
				menu-fonct-client
			;;
            *)
                PS3="`echo -e " \n Veuillez       faire       un       choix       valide :     "`"
            ;;
		esac	
    done 
} 

#SOUS  MENU  POUR  LE  MONTAGE
function menu-fonct-client-mont()
{
    resize -s 22 83
    clear
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t   FONCTIONNALITES   DU    CLIENT \t\t\t\t|"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t    MONTAGE   REPERTOIRE  DISTANT   \t \t \t\t|"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    montage
    menu-fonct-client-mont-termine
}

#SOUS  MENU  POUR  LE  DEMONTAGE
function menu-fonct-client-demont()
{
    resize -s 17 83
    clear
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t   FONCTIONNALITES   DU    CLIENT \t\t\t\t|"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t   DEMONTAGE   REPERTOIRE  DISTANT  \t \t \t\t|"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    demontage
    menu-fonct-client-demont-termine
}

# SOUS MENU POUR LE MONTAGE  TERMINEE
function menu-fonct-client-mont-termine()
{
    resize -s 17 83
    clear
    montage=0
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t   FONCTIONNALITES   DU    CLIENT \t\t\t\t|"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t       MONTAGE        TERMINEE   !!!\t \t \t\t|"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|   LE  MONTAGE  EST  TERMINE.  VOUS  POUVEZ  DESORMAIS  NAVIGUER  DANS   LE  RE- |"
    echo -e    "|                     PERTOIRE  EN   TOUTE  LIBERTE  !!!                          |"
    echo -e    "|                                                                                 |"
    echo -e    "|    APPUYEZ   SUR   UNE   TOUCHE   POUR  REVENIR   AU   MENU   PRINCIPAL !       |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    appui
    menu-mode-client  
}

# SOUS MENU POUR LE DEMONTAGE  TERMINEE
function menu-fonct-client-demont-termine()
{
    resize -s 17 83
    clear
    montage=1
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t   FONCTIONNALITES   DU    CLIENT \t\t\t\t|"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t   DEMONTAGE        TERMINEE   !!!  \t \t \t\t|"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|                      LE    DEMONTAGE    EST    TERMINE  !!!                     |"
    echo -e    "|                                                                                 |"
    echo -e    "|    APPUYEZ   SUR   UNE   TOUCHE   POUR  REVENIR   AU   MENU   PRINCIPAL !       |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    appui
    menu-mode-client  
}

#SOUS  MENU  POUR LA REDIRECTION VERS UN PORT DISTANT
function menu-fonct-client-redir-portloc()
{
    resize -s 26 83
    clear
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t   FONCTIONNALITES   DU    CLIENT \t\t\t\t|"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t      REDIRECTION  DES   PORTS \t \t \t\t  |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t       REDIRECTION PORT LOCAL  \t \t \t\t  |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    redirection-loc
    echo -e    " \n  APPUYEZ   SUR    UNE    TOUCHE   POUR    REVENIR   AUX    FONCTIONNALITES     "
    appui
    menu-fonct-client
}   

#SOUS  MENU  POUR LA SECURISATION
function menu-fonct-client-redir-secur()
{
    resize -s 24 83
    clear
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t   FONCTIONNALITES   DU    CLIENT \t\t\t\t|"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t      REDIRECTION  DES   PORTS \t \t \t\t  |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t       SECURISATION PORT DISTANT\t\t \t\t|"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    securisation
    echo -e    "\n           LA   SECURISATION   DU   PORT    A    ETE    EFFECTUE   !!!\n           " 
    echo -e    "   APPUYEZ   SUR    UNE    TOUCHE   POUR    REVENIR   AUX    FONCTIONNALITES       "
    appui
    menu-fonct-client
}

# SOUS MENU POUR LA REDIRECTION
function menu-fonct-client-redir()
{
    resize -s 28 83
    clear
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t   FONCTIONNALITES   DU    CLIENT \t\t\t\t|"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t\t\t      REDIRECTION  DES   PORTS \t \t \t\t  |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|  LA  REDIRECTION  VOUS  PERMETTRA  D' UTILISER  UN  PORT  DU  SERVEUR  SUR  VO- |"
    echo -e    "|                           TRE  POSTE   CLIENT.                                  |"
    echo -e    "|  LA  SECURISATION VOUS  PERMETTRA  DE REMPLACER  DE REMPLACER  UN PORT DE VOTRE |"
    echo -e    "|   SERVEUR  PAR  UN  AUTRE  AFIN  DE  LE  GARDER  SECRET  ET LIMITER  L' ACCESS  |"
    echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
     echo -e "\n"
    
    #VARIABLES DU MENU

    me1="\t Redirection  \t  port  \tlocal \n\n"
    me2="\t Securisation  \t  port  \tdistant \n"
    me3="\t Retourner  \t  aux  \t        fonctionnalites "

    me1=`echo -e "$me1"`
    me2=`echo -e "$me2"`
    me3=`echo -e "$me3"`
    
    #CHOIX DU MENU

    PS3="`echo -e " \n\n\n Veuillez \t faire  \t  votre  \t  choix :     "`"

    select var in "$me1" "$me2" "$me3"
    do 
        case $REPLY in 
			1)	
                menu-fonct-client-redir-portloc		
                break
            ;;
    		2)
                menu-fonct-client-redir-secur		
                break
			;;
        	3)	
				menu-fonct-client
			;;
            *)
                PS3="`echo -e " \n Veuillez       faire       un       choix       valide :     "`"
            ;;
		esac	
    done   
}

# FONCTION DU MENU DES FONCTIONNALITES DU CLIENT
function menu-fonct-client()
{
    resize -s 18 83
    clear
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t   FONCTIONNALITES   DU    CLIENT \t\t\t\t|"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e "\n \n"
    
    #VARIABLES DU MENU

    me1="\t Transfert  \t  de  \t          fichiers \n\n"
    me2="\t Montage  \t  repertoire  \t  distant \n"
    me3="\t Demontage  \t  repertoire  \t  distant \n"
    me4="\t Redirection  \t  de  \t          ports \n"
    me5="\t Revenir  \t  au  \t          mode  Client  \n"
    me6="\t Quitter"
 
    me1=`echo -e "$me1"`
    me2=`echo -e "$me2"`
    me3=`echo -e "$me3"`
    me4=`echo -e "$me4"`
    me5=`echo -e "$me5"`
    me6=`echo -e "$me6"`
    
    #CHOIX DU MENU

    PS3="`echo -e " \n\n Veuillez \t faire  \t  votre  \t  choix :     "`"

    select var in "$me1" "$me2" "$me3" "$me4" "$me5" "$me6"
    do 
        case $REPLY in 
			1)	
                menu-fonct-client-transf		
                break
            ;;
    		2)
                menu-fonct-client-mont		
                break
			;;
            3)
                if [ $montage -eq 1 ] 
                    then
                        echo -e " \n Vous   devez   d'   abord    monter    un   repertoire    !"
                    else
                        menu-fonct-client-demont
                        break
                fi
			;;
        	4)
                menu-fonct-client-redir		
                break
			;;
            5)
                menu-mode-client	
                break
			;;
            6)	
				exit
			;;
            *)
                PS3="`echo -e " \n Veuillez       faire       un       choix       valide :     "`"
            ;;
		esac	
    done
}
