#!/bin/bash
function appui()
{
    x='ab';while [[ "$x" == "ab" ]]; do read -n1 x; done 
}

function gener-cles()
{
	echo -e "-----------------------------------------------------------------------------------"
	echo -e "\t GENERATION DES CLES EN COURS !!! IL VOUS SERA DEMANDE D' ENTREZ  UNE "
	echo -e "\t   UNE PASSPHRASE QUI VOUS REMPLACERA LE MOT DE PASSE DU COMPTE SER-  "
	echo -e "\t           VEUR. ELLE DOIT CONTENIR AU MOINS 5 CARACTERES             " 
	echo -e "-----------------------------------------------------------------------------------\n\n"
	ssh-keygen -f ~/Bureau/key >> log.txt 2>&1
	if [ $? -ne 0 ] 
	then
		echo -e "\n\t UN PROBLEME EST SURVENU LORS DE LA GENERATION. VEUILLEZ REESAYER "
		echo -e "\t       ULTERIEUREMENT. APPUYEZ SUR UNE TOUCHE POUR REVENIR AU     "
		echo -e "\t                          MENU PRINCIPAL !                        "
		appui
		#menu-mode-client
	else
		echo -e "\n\t          GENERATION  DE LA PAIRE  DE CLES EFFECTUEE !!!"
		echo -e "\t             --------------------------------------        \n"
	fi
}

gener-cles

	
	