#!/bin/bash

function affiche()
{
    clear
    echo "Entrez votre nom"
    read x
    echo "Vous vous appellez $x"
    
}

function menu-mode-client()
{
    resize -s 18 83
    clear
    echo -e    "|*********************************************************************************|"
    echo -e    "|                                                                                 |"
    echo -e    "|\t \t \t       MODE        CLIENT    \t  \t \t \t  |"
	echo -e    "|                                                                                 |"
	echo -e    "|*********************************************************************************|"
    echo -e "\n \n"
    
    #VARIABLES DU MENU

    me1="\t Configurer  \t          le  \t  client \n\n"
    me2="\t Fonctionnalites  \t  du  \t  serveur \n"
    me3="\t Quitter"

    me1=`echo -e "$me1"`
    me2=`echo -e "$me2"`
    me3=`echo -e "$me3"`
    
    #CHOIX DU MENU

    PS3="`echo -e " \n Veuillez \t faire  \t  votre  \t  choix : "`"

    select var in "$me1" "$me2" "$me3"
    do 
        case $REPLY in 
			1)
				clear	
                menu-config-client		
                break
            ;;
    		2)
                clear
                menu-fonct-serveur
                break
			;;
        	3)	
				exit
			;;
            *)
                PS3="`echo -e " \n Veuillez       faire       un       choix       valide : "`"
            ;;
		esac	
    done
}

menu-mode-client
echo "BOnjour"